### PR TITLE
Date long argtypes

### PR DESCRIPTION
**Pull request by JackSullivan**
This is an initial stab of setting this up, which is probably not ready for primetime. I haven't tested it, but I think I've gotten all the instances where Attributes are converted.

### CODE REVIEW

**Comment by JackSullivan** [comment]
Referencing #6

**Comment by stephenbach** [comment]
Thanks! I'm merging this in now, because it's unlikely to break any existing functionality.

**Comment by stephenbach** [comment]
Should line 146 of https://github.com/linqs/psl/blob/5afdcb5d60c2aa1201a713ed119d42917613fc6d/psl-core/src/main/java/edu/umd/cs/psl/util/database/Queries.java create a LongAttribute?

**Comment by JackSullivan** [comment]
You are correct, see #8

**Comment by stephenbach** [comment]
Thanks for the fix!

**Pull request merged**
